//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_peliculas
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<decimal> duracion { get; set; }
        public Nullable<int> idgenero { get; set; }
    
        public virtual tbl_genero tbl_genero { get; set; }
    }
}
